### ISSUE TITLE
What makes author pages generate?

### ISSUE THREAD

**Issue by atuttle** [biomadeira/jasper#3]
I changed my author name, bio, and username in _config.yml, even restarted jekyll, and my author page doesn't seem to be generated. Am I missing something?

**Comment by biomadeira** [comment]
@atuttle Sorry you faced that problem... I need to improve the documentation, because it is not very obvious what the problem is. 

Basically Jekyll has some methods implemented for posts, tags and categories and I used the later as a trick to be able to generated the author pages. (See the code ruby gem jekyll_autgenerator.rb in _plugins) 

For it to work with your pages simply change the 'categories: your username' in the front matter of every post and it should work fine. As you can see, it currently matches 'casper' which was the username specified in the _config.yml.

(This actually enables you to have multiple authors, but I doubt you need that...)

Let me know if this worked for you :)

**Comment by atuttle** [comment]
What about if I want to show my about content (e.g. `about.md -> about.html`) on the author page, rather than a list of blog posts (my blog will be single author, so that makes more sense)
